torchnet/transform.py

Reverts pytorch/tnt#2
reverted on the request of @willfrey

Revert "Update transform.py"

---

.gitignore
setup.py
test/datasets.py
test/meter.py
torchnet/dataset/tensordataset.py
torchnet/meter/classerrormeter.py
torchnet/transform.py

Made code compatible with Python3. I had to add `six` as a dependency, which is reflected in the updated `setup.py` file. I also added `torch` as an explicit dependency in `setup.py`.
I updated the tests to work with Python2 and Python3.
I added a `.gitignore` file to help keep commits slightly cleaner but it might miss different compiled python objects, etc. It should probably be expanded.
All of the tests pass for me using my conda environment for both Python2 and Python3.

Added Python3 support + misc. changes.

---

torchnet/engine/engine.py

Don't hold pointers to previous states

Improve memory usage

---

README.md
test/test_meters.py
torchnet/meter/__init__.py
torchnet/meter/classerrormeter.py
torchnet/meter/movingaveragevaluemeter.py
torchnet/meter/msemeter.py

* MSEMeter
* MovingAverageValueMeter
* ClassErrorMeter accepts numpy and target number

More meters and other improvements

---

test/test_meters.py
torchnet/meter/__init__.py
torchnet/meter/aucmeter.py

Added auc meter with tests. Most code is taken from [aucmeter.lua](https://github.com/torchnet/torchnet/blob/master/meter/aucmeter.lua). 
- Area is calculated in a trapezoidal way rather than rectangular
- Tests are exactly same as in [torchnet](https://github.com/torchnet/torchnet/blob/master/test/meters.lua#L155)

Added AUCMeter 

---

README.md

Modified README with updated list of meters available

---

test/test_meters.py
torchnet/meter/__init__.py
torchnet/meter/apmeter.py
torchnet/meter/mapmeter.py

Just adding two PyTorch meters (and corresponding tests) converted from lua [torchnet](https://github.com/torchnet/torchnet):
* APMeter
* mAPMeter

Add APMeter and mAPMeter

---

torchnet/engine/engine.py

This PR add a hook 'on_update' in the engine. This might be helpful for showing real time loss&acc update

Add hook 'on_update'

---

example/mnist_with_visdom.py
requirements.txt
setup.py
torchnet/__init__.py
torchnet/logger/__init__.py
torchnet/logger/logger.py
torchnet/logger/visdomlogger.py

Added the ability to log to [Visdom](https://github.com/facebookresearch/visdom/) (like Tensorboard, but better!). It is a port of [this repo](https://github.com/alexsax/pytorch-nice) to TNT. 
This PR adds TNT support for the existing Visdom plots and includes an example that uses it for MNIST (above).

Add Visdom logging to TNT

---

torchnet/meter/confusionmeter.py

Used bin count hack for 2d arrays to calculate confusion matrix for making computation fast when n is large in predicted output tensor of model (n x k) and also made add function to work even when output is an n-tensor

Modified confusion meter.py

---

example/mnist.py
example/mnist_with_visdom.py
test/test_datasets.py
test/test_meters.py
test/test_transforms.py
torchnet/dataset/shuffledataset.py
torchnet/dataset/splitdataset.py
torchnet/engine/engine.py
torchnet/logger/logger.py
torchnet/logger/visdomlogger.py
torchnet/meter/apmeter.py
torchnet/meter/aucmeter.py
torchnet/meter/averagevaluemeter.py
torchnet/meter/classerrormeter.py
torchnet/meter/mapmeter.py
torchnet/meter/movingaveragevaluemeter.py
torchnet/meter/timemeter.py
torchnet/transform.py
torchnet/utils/table.py

```line 26
return self.mean, self.std
^
TabError: inconsistent use of tabs and spaces in indentation```
Also, PEP8

fixed inconsistent use of tabs and spaces in indentation

---

torchnet/__init__.py
torchnet/dataset/listdataset.py
torchnet/logger/meterlogger.py
torchnet/logger/visdomlogger.py
torchnet/meter/apmeter.py
torchnet/meter/aucmeter.py
torchnet/meter/mapmeter.py
torchnet/transform.py

https://github.com/pytorch/tnt/pull/55 breaks py3 as it mixes space and tabs and does not follow pep8, this fixes it and a few other pep8 issues

fix lint and indentation

---

example/mnist.py
example/mnist_with_meterlogger.py
example/mnist_with_visdom.py
test/test_datasets.py
test/test_meters.py
test/test_transforms.py
torchnet/__init__.py
torchnet/logger/meterlogger.py
torchnet/logger/visdomlogger.py
tox.ini

A few fixes:
* fix mnist examples to work with py3
* fix other spaces and tabs issue with examples
* add tox.ini (copied from pytorch)
* improve tests a little bit

Continue pep8, add tox.ini

---

.travis.yml
requirements.txt

taken from https://github.com/uber/pyro/blob/dev/.travis.yml thanks @soumith

Add py3 and flake8 to travis

---

test/test_meters.py
torchnet/meter/averagevaluemeter.py

fix conflicts of https://github.com/pytorch/tnt/pull/52

Stable averagevaluemeter

---

README.md

Note on how to update tnt

---

example/mnist_with_meterlogger.py
torchnet/logger/meterlogger.py

Remove camelCase from meterlogger

---

test/test_meters.py
torchnet/meter/averagevaluemeter.py

Related to #71 
Only handles the mean component. I couldn't find any literature around online batch variance.

Correcting averagevaluemeter when n>1

---

torchnet/logger/visdomlogger.py

Visdom have removed the function updateTrace and set it an argument in plot functions. I updated the corresponding part of the Log function in the VisdomPlotter.

Update VisdomPlotLogger because of the removal of updateTrace from visdom

---

README.md

Added https to fix the broken link leading to documentation

Fix broken Link

---

test/test_meters.py
torchnet/meter/averagevaluemeter.py

- Fixes #100
- Added tests to for AverageValueMeter with 2D tensors, numpy arrays

Make AverageValueMeter play nice with Tensors and Numpy arrays

---

torchnet/logger/meterlogger.py

fix deprecated loss access

---

tox.ini

W504 and W503 are conflicting, adding W504 to ignore to fix Travis

Add W504 to ignore

---

torchnet/utils/resultswriter.py

Line 41 throws an error if you do not import os library

Update resultswriter.py to import os
